### ISSUE TITLE
google/apiclient-services[v0.11] ???

### ISSUE THREAD

**Issue by edilsonsilvapro** [Rhincodon/laravel-eloquent-spreadsheets#13]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: google/apiclient-services[v0.8, v0.11].
    - Can only install one of: google/apiclient-services[v0.8, v0.11].
    - Can only install one of: google/apiclient-services[v0.8, v0.11].
    - rhincodon/laravel-eloquent-spreadsheets 0.1.4 requires google/apiclient-services ^0.8.0 -> satisfiable by google/apiclient-services[v0.8].
    - Installation request for rhincodon/laravel-eloquent-spreadsheets ^0.1.4 -> satisfiable by rhincodon/laravel-eloquent-spreadsheets[0.1.4].
    - Installation request for google/apiclient-services (locked at v0.11) -> satisfiable by google/apiclient-services[v0.11].

**Comment by Rhincodon** [comment]
Fixed in [0.1.5](https://github.com/Rhincodon/laravel-eloquent-spreadsheets/tree/0.1.5)
